### PR TITLE
Feature/concert response js (Do not merge yet)

### PR DESCRIPTION
**Pull request by gthornbuckle**
Chris please can you look at this branch when you get chance, I've tried to simplify the js into separate files. 
The way it's currently set up you should be able to press the search button (no input needed right now) and it should display the results page with the test data. 
However I think switching the html page stops the code from running so it doesn't work properly.
I've had a look around and I can't see a simple solution to switch pages without triggering a refresh which prevents the code from running, unless I'm missing something obvious.
One solution I know would work is to just have everything in the index.html and hide the different elements as required but if you know a better way or how to make this way work let me know.

Cheers

### CODE REVIEW

**Comment by Chriscds** [comment]
> Chris please can you look at this branch when you get chance, I've tried to simplify the js into separate files. The way it's currently set up you should be able to press the search button (no input needed right now) and it should display the results page with the test data. However I think switching the html page stops the code from running so it doesn't work properly. I've had a look around and I can't see a simple solution to switch pages without triggering a refresh which prevents the code from running, unless I'm missing something obvious. One solution I know would work is to just have everything in the index.html and hide the different elements as required but if you know a better way or how to make this way work let me know.
> 
> Cheers

Hi George. I will take a look. I think there is something called window.location.assign that is used for cases like, just don't hold me to that.

Thanks

**Comment by Chriscds** [comment]
From what I can see, it can be done when using server side storage. There's a couple of ways:

1. As you suggested, with hidden results window that is show on search click.
2. Using local storage for all of the inputs to then get results on the results.html

I'm thinking the first option may be the best one for this. Let me know what you think.

Cheers

**Comment by gthornbuckle** [comment]
Yes I think we should go with the first option, otherwise we'll have to deal with temporary data in local storage which then has to be removed later. I can create CSS classes for "hidden" and "visible" like we had in the code quiz and just toggle them based on when they're needed.
I'm thinking we can still have multiple html files but the results page can be changed to a "Saved events" page. So all it'll have to do is read the local storage and generate html elements from that, like how the high scores page worked in the code quiz.

So the way the app will work based on this is:
1. User inputs artist name, address and country. "Search" button and "View saved" button.
2. Pressing search stores input data in a temporary array so it can be accessed by the other javascript files
3. If the data passes all the validation (artist exists, artist has an event in specified country) then the input form is hidden and replaced with the carousel and map form that's currently on the results page
4. The events are displayed in the carousel with "Directions" and "Save" buttons
5. Pressing the "Directions" button will call the routing API and take the inputted user address and convert it to lat/long coordinates and then display a route to the event using the map API.
6. Pressing the save button will take all the event info on the card, and the user's inputted lat/long and save them to local storage.
7. If the user comes back to the site and presses the "View saved" button it takes them to another html page which just displays the event info and map like normal

**Review by Chriscds — APPROVED** [review]
Okay, lets go with that first option.

**Pull request closed without merging**
